### PR TITLE
Improve documentation and errors for problems with the map style

### PR DESCRIPTION
**Pull request by jjhembd**
- README.md: Add (incomplete) list of unsupported features
- package.json: Update tile-stencil to improve error messages for
  style loading, and allow rendering of styles for which one source
  or sprite is not accessible
- src/main.js: Do not .catch errors on init--leave this to the
  example code

This should address the last point in #1. If there are problems with the user's style document, the error messages will now be more explanatory. And the README points to the limitations in the dependent modules, to clarify what subset of the specification is supported.

### CODE REVIEW

**Comment by jjhembd** [comment]
See https://globeletjs.github.io/tile-stencil/examples/validator/index.html for an example of the new error handling in tile-stencil. You can plug in this style
https://globeletjs.org/examples/geojson/klokantech-basic-style-geojson.json
and open Chrome Dev Tools to see the error messages when only some of the sources are not accessible.

The current behavior (before this PR) is for everything to crash with no clear error. This PR will still load the globe, even though not all the layers are available.

**Comment by jjhembd** [comment]
The bundle size has gone down by some 900 lines. The deleted lines are mostly Turf.js code that wasn't being used.

I updated the Rollup version for many of the dependent modules. I think the new version of Rollup may be doing a better job of deleting unused code

**Review by ananya-roy — APPROVED** [review]
I like the style checker. Is it possible to set it up to load a local file? (In case the user wants to check if things are in order before setting up an example.)

**Comment by jjhembd** [comment]
> I like the style checker. Is it possible to set it up to load a local file? (In case the user wants to check if things are in order before setting up an example.)

This sounds like a good idea. It would be a change to an example in tile-stencil, so I opened an issue there.
https://github.com/GlobeletJS/tile-stencil/issues/6

Adding this to the example in tile-stencil would not affect the code that is imported to GlobeletJS, so I will go ahead and merge what we have now.

**Pull request merged**
